// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<Pending>", Scope = "member", Target = "~M:JobSearchCodeExamples.cs.Test.Contest.LeetCodeContest307Test.AmountOfTimeTest(System.Nullable{System.Int32}[],System.Int32,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<Pending>", Scope = "member", Target = "~M:JobSearchCodeExamples.cs.Test.Contest.LeetCodeContest307Test.KSumTest(System.Int32[],System.Int32,System.Int64)")]
[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "<Pending>", Scope = "member", Target = "~P:JobSearchCodeExamples.cs.Test.Contest.LeetCodeContest307Test.AmountOfTimeTestData")]
[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "<Pending>", Scope = "member", Target = "~P:JobSearchCodeExamples.cs.Test.Contest.LeetCodeContest307Test.MinNumberOfHoursTestData")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<Pending>", Scope = "member", Target = "~M:JobSearchCodeExamples.cs.Test.Contest.LeetCodeContest309Test.CheckDistancesTest(System.String,System.Int32[],System.Boolean)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<Pending>", Scope = "member", Target = "~M:JobSearchCodeExamples.cs.Test.Contest.LeetCodeContest309Test.NumberOfWaysTest(System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<Pending>", Scope = "member", Target = "~M:JobSearchCodeExamples.cs.Test.Contest.LeetCodeContest309Test.LongestNiceSubArrayTest(System.Int64[],System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<Pending>", Scope = "member", Target = "~M:JobSearchCodeExamples.cs.Test.Contest.LeetCodeContest309Test.MostBookedBruteForceTest(System.Int32,System.Int32[][],System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<Pending>", Scope = "member", Target = "~M:JobSearchCodeExamples.cs.Test.Contest.LeetCodeContest309Test.MostBookedPriorityQueueTest(System.Int32,System.Int32[][],System.Int32)")]
[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "<Pending>", Scope = "member", Target = "~P:JobSearchCodeExamples.cs.Test.Contest.LeetCodeContest309Test.CheckDistancesTestData")]
[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "<Pending>", Scope = "member", Target = "~P:JobSearchCodeExamples.cs.Test.Contest.LeetCodeContest307Test.KSumTestData")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<Pending>", Scope = "member", Target = "~M:JobSearchCodeExamples.cs.Test.Contest.LeetCodeContest307Test.MinNumberOfHoursTest(System.Int32,System.Int32,System.Int32[],System.Int32[],System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<Pending>", Scope = "member", Target = "~M:JobSearchCodeExamples.cs.Test.Contest.LeetCodeContest307Test.KSum2Test(System.Int32[],System.Int32,System.Int64)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<Pending>", Scope = "member", Target = "~M:JobSearchCodeExamples.cs.Test.Contest.LeetCodeContest313.Question1Test.CommonFactorsTest(System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<Pending>", Scope = "member", Target = "~M:JobSearchCodeExamples.cs.Test.Contest.LeetCodeContest313.Question2Test.MaxSumTest(System.Int32[][],System.Int32)")]
[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "<Pending>", Scope = "member", Target = "~P:JobSearchCodeExamples.cs.Test.Contest.LeetCodeContest313.Question2Test.MaxSumTestData")]
[assembly: SuppressMessage("Style", "IDE0300:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~P:JobSearchCodeExamples.cs.Test.Contest.LeetCodeContest313.Question2Test.MaxSumTestData")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<Pending>", Scope = "member", Target = "~M:JobSearchCodeExamples.cs.Test.Contest.LeetCodeContest313.Question3Test.MinimizeXorTest(System.Int32,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Usage", "xUnit1042:The member referenced by the MemberData attribute returns untyped data rows", Justification = "<Pending>", Scope = "member", Target = "~M:JobSearchCodeExamples.cs.Test.Contest.LeetCodeContest313.Question4Test.DeleteStringTest(System.String,System.Int32)")]
