<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>

    <Platforms>AnyCPU;x64;x86;ARM32;ARM64</Platforms>

  </PropertyGroup>

  <PropertyGroup Condition="'$(Platform)'!='AnyCPU'">
    <OutputPath>..\Build\$(Platform)\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Platform)'=='AnyCPU'">
    <OutputPath>..\Build\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="TestData\KSumTestData\LargeArray09.json" />
    <None Remove="TestData\KSumTestData\LargeArray10.json" />
    <None Remove="TestData\KSumTestData\LargeArray11.json" />
    <None Remove="TestData\KSumTestData\LargeArray12.json" />
    <None Remove="TestData\KSumTestData\LargeArray13.json" />
    <None Remove="TestData\KSumTestData\LargeArray14.json" />
    <None Remove="TestData\KSumTestData\LargeArray15.json" />
    <None Remove="TestData\KSumTestData\LargeArray16.json" />
    <None Remove="TestData\KSumTestData\LargeArray17.json" />
    <None Remove="TestData\KSumTestData\LargeArray18.json" />
    <None Remove="TestData\KSumTestData\LargeArray19.json" />
    <None Remove="TestData\KSumTestData\LargeArray20.json" />
    <None Remove="TestData\KSumTestData\LargeArray21.json" />
    <None Remove="TestData\KSumTestData\LargeArray22.json" />
    <None Remove="TestData\KSumTestData\LargeArray23.json" />
    <None Remove="TestData\KSumTestData\LargeArray24.json" />
    <None Remove="TestData\KSumTestData\LargeArray25.json" />
    <None Remove="TestData\KSumTestData\LargeArray26.json" />
    <None Remove="TestData\KSumTestData\LargeArray27.json" />
    <None Remove="TestData\KSumTestData\LargeArray28.json" />
    <None Remove="TestData\KSumTestData\LargeArray29.json" />
    <None Remove="TestData\KSumTestData\LargeArray30.json" />
    <None Remove="TestData\KSumTestData\LargeArray31.json" />
    <None Remove="TestData\KSumTestData\LargeArray32.json" />
    <None Remove="TestData\KSumTestData\LargeArray33.json" />
    <None Remove="TestData\KSumTestData\LargeArray34.json" />
    <None Remove="TestData\KSumTestData\LargeArray35.json" />
    <None Remove="TestData\KSumTestData\LargeArray36.json" />
    <None Remove="TestData\KSumTestData\LargeArray37.json" />
    <None Remove="TestData\KSumTestData\LargeArray38.json" />
    <None Remove="TestData\KSumTestData\LargeArray39.json" />
    <None Remove="TestData\KSumTestData\LargeArray40.json" />
    <None Remove="TestData\LongestNiceSubArrayTestData\LargeArray08.json" />
    <None Remove="TestData\LongestNiceSubArrayTestData\LargeArray10.json" />
    <None Remove="TestData\LongestNiceSubArrayTestData\LargeArray11.json" />
    <None Remove="TestData\LongestNiceSubArrayTestData\LargeArray12.json" />
    <None Remove="TestData\LongestNiceSubArrayTestData\LargeArray13.json" />
    <None Remove="TestData\LongestNiceSubArrayTestData\LargeArray14.json" />
    <None Remove="TestData\LongestNiceSubArrayTestData\LargeArray15.json" />
    <None Remove="TestData\LongestNiceSubArrayTestData\LargeArray16.json" />
    <None Remove="TestData\LongestNiceSubArrayTestData\LargeArray17.json" />
    <None Remove="TestData\LongestNiceSubArrayTestData\LargeArray18.json" />
    <None Remove="TestData\LongestNiceSubArrayTestData\LargeArray19.json" />
    <None Remove="TestData\LongestNiceSubArrayTestData\LargeArray20.json" />
    <None Remove="TestData\LongestNiceSubArrayTestData\LargeArray21.json" />
    <None Remove="TestData\LongestNiceSubArrayTestData\LargeArray22.json" />
    <None Remove="TestData\LongestNiceSubArrayTestData\LargeArray23.json" />
    <None Remove="TestData\LongestNiceSubArrayTestData\LargeArray24.json" />
    <None Remove="TestData\LongestNiceSubArrayTestData\LargeArray25.json" />
    <None Remove="TestData\LongestNiceSubArrayTestData\LargeArray26.json" />
    <None Remove="TestData\LongestNiceSubArrayTestData\LargeArray27.json" />
    <None Remove="TestData\MostBookedTestData\LargeArray1.json" />
    <None Remove="TestData\MostBookedTestData\LargeArray2.json" />
    <None Remove="TestData\MostBookedTestData\LargeArray3.json" />
    <None Remove="TestData\MostBookedTestData\LargeArray4.json" />
    <None Remove="TestData\MostBookedTestData\LargeArray5.json" />
    <None Remove="TestData\MostBookedTestData\LargeArray6.json" />
    <None Remove="TestData\MostBookedTestData\LargeArray7.json" />
    <None Remove="TestData\MostBookedTestData\LargeArray8.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="TestData\AmountOfTimeData\LargeTree1.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray01.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray02.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray03.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray04.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray05.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray06.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray07.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray08.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray09.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray10.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray11.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray12.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray13.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray14.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray15.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray16.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray17.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray18.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray19.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray20.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray21.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray22.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray23.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray24.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray25.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray26.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray27.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray28.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray29.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray30.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray31.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray32.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray33.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray34.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray35.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray36.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray37.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray38.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray39.json" />
    <EmbeddedResource Include="TestData\KSumTestData\LargeArray40.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray01.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray02.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray03.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray04.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray05.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray06.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray07.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray08.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray09.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray10.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray11.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray12.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray13.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray14.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray15.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray16.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray17.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray18.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray19.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray20.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray21.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray22.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray23.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray24.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray25.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray26.json" />
    <EmbeddedResource Include="TestData\LongestNiceSubArrayTestData\LargeArray27.json" />
    <EmbeddedResource Include="TestData\MostBookedTestData\LargeArray1.json" />
    <EmbeddedResource Include="TestData\MostBookedTestData\LargeArray2.json" />
    <EmbeddedResource Include="TestData\MostBookedTestData\LargeArray3.json" />
    <EmbeddedResource Include="TestData\MostBookedTestData\LargeArray4.json" />
    <EmbeddedResource Include="TestData\MostBookedTestData\LargeArray5.json" />
    <EmbeddedResource Include="TestData\MostBookedTestData\LargeArray6.json" />
    <EmbeddedResource Include="TestData\MostBookedTestData\LargeArray7.json" />
    <EmbeddedResource Include="TestData\MostBookedTestData\LargeArray8.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\ExecCodeCoverage.ps1" Link="ExecCodeCoverage.ps1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="ReportGenerator" Version="5.5.10" />
    <PackageReference Include="Verify.Xunit" Version="31.12.5" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.analyzers" Version="1.27.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.console" Version="2.9.3" />
    <PackageReference Include="xunit.runner.utility" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JobSearchCodeExamples.Support\JobSearchCodeExamples.Support.csproj" />
    <ProjectReference Include="..\JobSearchCodeExamples\JobSearchCodeExamples.cs.csproj" />
  </ItemGroup>

</Project>
