<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Platforms>AnyCPU;x64;x86;ARM32;ARM64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Platform)'!='AnyCPU'">
    <OutputPath>..\Build\$(Platform)\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Platform)'=='AnyCPU'">
    <OutputPath>..\Build\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="TestTaker\LeetCode.fs" />
    <Compile Include="TestTaker\LongVersion.fs" />
    <Compile Include="TestTaker\CustomCode.fs" />
    <Compile Include="TestTaker\EmployeeCoverage.fs" />
    <Compile Include="TestTaker\KWeakestRowsInAMatrix.fs" />
    <Compile Include="TestTaker\LinkedList.fs" />
    <Compile Include="TestTaker\RansomNode.fs" />
    <Compile Include="TestTaker\ToInt.fs" />
    <Compile Include="TheaterSeats.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="10.1.302" />
  </ItemGroup>

</Project>
