using JobSearchCodeExamples.cs.Test.Support;

namespace JobSearchCodeExamples.cs.Test.Contest;

public partial class LeetCodeContest309Test
{
    /// <summary>
    /// Gets the test data.
    /// </summary>
    /// <value>
    /// The test data.
    /// </value>
    public static IEnumerable<object[]> MostBookedTestData
    {
        get
        {
            var result = new List<object[]>
            {
                new object[] { 1,
                    new int[][] { new int[] { 0, 1 } },
                    0 },
                new object[] { 1,
                    new int[][] { new int[] { 3, 13 },
                                  new int[] { 0, 17 } },
                    0 },
                new object[] { 1,
                    new int[][] { new int[] { 10, 19 },
                                  new int[] { 17, 20 } },
                    0 },
                new object[] { 1,
                    new int[][] { new int[] { 3, 19 },
                                  new int[] { 7, 13 },
                                  new int[] { 16, 18 },
                                  new int[] { 10, 17 } },
                    0 },
                new object[] { 1,
                    new int[][] { new int[] { 4, 35 },
                                  new int[] { 49, 50 },
                                  new int[] { 34, 36 },
                                  new int[] { 2, 44 },
                                  new int[] { 39, 44 } },
                    0 },
                new object[] { 1,
                    new int[][] { new int[] { 7, 15 },
                                  new int[] { 13, 18 },
                                  new int[] { 14, 20 },
                                  new int[] { 0, 6 } },
                    0 },
                new object[] { 1,
                    new int[][] { new int[] { 12, 14 },
                                  new int[] { 4, 11 },
                                  new int[] { 16, 18 },
                                  new int[] { 3, 11 } },
                    0 },
                new object[] { 1,
                    new int[][] { new int[] { 0, 19 },
                                  new int[] { 9, 11 },
                                  new int[] { 14, 20 },
                                  new int[] { 7, 13 },
                                  new int[] { 17, 20 } },
                    0 },
                new object[] { 1,
                    new int[][] { new int[] { 17, 26 },
                                  new int[] { 35, 36 },
                                  new int[] { 10, 30 },
                                  new int[] { 45, 50 },
                                  new int[] { 28, 43 },
                                  new int[] { 48, 50 },
                                  new int[] { 3, 20 },
                                  new int[] { 12, 24 },
                                  new int[] { 31, 44 } },
                    0 },
                new object[] { 1,
                    new int[][] { new int[] { 21, 48 },
                                  new int[] { 47, 49 },
                                  new int[] { 28, 37 },
                                  new int[] { 22, 40 },
                                  new int[] { 32, 46 },
                                  new int[] { 13, 41 },
                                  new int[] { 2, 37 } },
                    0 },
                new object[] { 1,
                    new int[][] { new int[] { 22, 45 },
                                  new int[] { 36, 41 },
                                  new int[] { 32, 34 },
                                  new int[] { 43, 47 },
                                  new int[] { 31, 36 },
                                  new int[] { 14, 32 },
                                  new int[] { 45, 49 },
                                  new int[] { 4, 14 },
                                  new int[] { 28, 44 } },
                    0 },
                new object[] { 1,
                    new int[][] { new int[] { 27, 37 },
                                  new int[] { 20, 34 },
                                  new int[] { 7, 37 },
                                  new int[] { 13, 14 },
                                  new int[] { 6, 41 } },
                    0 },
                new object[] { 1,
                    new int[][] { new int[] { 28, 39 },
                                  new int[] { 8, 49 },
                                  new int[] { 43, 47 },
                                  new int[] { 2, 36 },
                                  new int[] { 7, 31 },
                                  new int[] { 12, 38 },
                                  new int[] { 24, 30 },
                                  new int[] { 29, 48 },
                                  new int[] { 45, 47 } },
                    0 },
                new object[] { 1,
                    new int[][] { new int[] { 30, 49 },
                                  new int[] { 15, 49 },
                                  new int[] { 32, 47 },
                                  new int[] { 41, 42 },
                                  new int[] { 38, 49 },
                                  new int[] { 17, 35 } },
                    0 },
                new object[] { 1,
                    new int[][] { new int[] { 30, 49 },
                                  new int[] { 15, 49 },
                                  new int[] { 9, 22 },
                                  new int[] { 24, 30 },
                                  new int[] { 12, 23 },
                                  new int[] { 43, 49 },
                                  new int[] { 36, 46 },
                                  new int[] { 6, 21 },
                                  new int[] { 0, 20 },
                                  new int[] { 17, 35 } },
                    0 },
                new object[] { 1,
                    new int[][] { new int[] { 39, 40 },
                                  new int[] { 27, 34 },
                                  new int[] { 28, 48 },
                                  new int[] { 31, 43 },
                                  new int[] { 15, 30 },
                                  new int[] { 3, 11 },
                                  new int[] { 22, 37 },
                                  new int[] { 7, 24 } },
                    0 },
                new object[] { 2,
                    new int[][] { new int[] { 0, 10 },
                                  new int[] { 1, 5 },
                                  new int[] { 2, 7 },
                                  new int[] { 3, 4 } },
                    0 },
                new object[] { 2,
                    new int[][] { new int[] { 4, 6 },
                                  new int[] { 5, 8 } },
                    0 },
                new object[] { 2,
                    new int[][] { new int[] { 4, 11 },
                                  new int[] { 1, 13 },
                                  new int[] { 8, 15 },
                                  new int[] { 9, 18 },
                                  new int[] { 0, 17 } },
                    1 },
                new object[] { 2,
                    new int[][] { new int[] { 4, 12 },
                                  new int[] { 7, 14 },
                                  new int[] { 10, 15 },
                                  new int[] { 14, 15 } },
                    0 },
                new object[] { 2,
                    new int[][] { new int[] { 8, 16 },
                                  new int[] { 17, 18 },
                                  new int[] { 6, 17 },
                                  new int[] { 0, 13 } },
                    0 },
                new object[] { 2,
                    new int[][] { new int[] { 8, 44 },
                                  new int[] { 14, 40 },
                                  new int[] { 0, 21 },
                                  new int[] { 21, 47 },
                                  new int[] { 32, 44 },
                                  new int[] { 1, 49 },
                                  new int[] { 18, 33 },
                                  new int[] { 17, 22 } },
                    0 },
                new object[] { 2,
                    new int[][] { new int[] { 9, 10 } },
                    0 },
                new object[] { 2,
                    new int[][] { new int[] { 10, 11 },
                                  new int[] { 2, 10 },
                                  new int[] { 1, 17 },
                                  new int[] { 9, 13 },
                                  new int[] { 18, 20 } },
                    1 },
                new object[] { 2,
                    new int[][] { new int[] { 43, 44 },
                                  new int[] { 34, 36 },
                                  new int[] { 11, 47 },
                                  new int[] { 1, 8 },
                                  new int[] { 30, 33 },
                                  new int[] { 45, 48 },
                                  new int[] { 23, 41 },
                                  new int[] { 29, 30 } },
                    1 },
                new object[] { 2,
                    new int[][] { new int[] { 48, 50 },
                                  new int[] { 38, 41 },
                                  new int[] { 17, 41 },
                                  new int[] { 17, 48 },
                                  new int[] { 10, 26 },
                                  new int[] { 16, 46 } },
                    0 },
                new object[] { 3,
                    new int[][] { new int[] { 1, 20 },
                                  new int[] { 2, 10 },
                                  new int[] { 3, 5 },
                                  new int[] { 4, 9 },
                                  new int[] { 6, 8 } },
                    1 },
                new object[] { 3,
                    new int[][] { new int[] { 0, 10 },
                                  new int[] { 1, 5 },
                                  new int[] { 2, 7 },
                                  new int[] { 3, 4 } },
                    1 },
                new object[] { 3,
                    new int[][] { new int[] { 0, 18 },
                                  new int[] { 7, 11 } },
                    0 },
                new object[] { 3,
                    new int[][] { new int[] { 1, 27 },
                                  new int[] { 29, 49 },
                                  new int[] { 47, 49 },
                                  new int[] { 41, 43 },
                                  new int[] { 15, 36 },
                                  new int[] { 11, 15 } },
                    1 },
                new object[] { 3,
                    new int[][] { new int[] { 3, 7 },
                                  new int[] { 12, 19 },
                                  new int[] { 16, 17 },
                                  new int[] { 1, 17 },
                                  new int[] { 5, 6 } },
                    1 },
                new object[] { 3,
                    new int[][] { new int[] { 5, 12 },
                                  new int[] { 3, 15 },
                                  new int[] { 9, 11 } },
                    0 },
                new object[] { 3,
                    new int[][] { new int[] { 5, 44 },
                                  new int[] { 24, 29 },
                                  new int[] { 31, 48 },
                                  new int[] { 38, 48 },
                                  new int[] { 32, 47 },
                                  new int[] { 1, 13 },
                                  new int[] { 42, 47 } },
                    0 },
                new object[] { 3,
                    new int[][] { new int[] { 6, 47 },
                                  new int[] { 44, 48 },
                                  new int[] { 24, 48 },
                                  new int[] { 12, 15 },
                                  new int[] { 41, 43 } },
                    1 },
                new object[] { 3,
                    new int[][] { new int[] { 8, 13 },
                                  new int[] { 16, 19 },
                                  new int[] { 13, 19 } },
                    0 },
                new object[] { 3,
                    new int[][] { new int[] { 13, 16 },
                                  new int[] { 12, 19 } },
                    0 },
                new object[] { 3,
                    new int[][] { new int[] { 13, 20 },
                                  new int[] { 5, 17 },
                                  new int[] { 17, 19 } },
                    0 },
                new object[] { 3,
                    new int[][] { new int[] { 14, 19 } },
                    0 },
                new object[] { 3,
                    new int[][] { new int[] { 18, 19 } },
                    0 },
                new object[] { 3,
                    new int[][] { new int[] { 39, 49 },
                                  new int[] { 22, 37 },
                                  new int[] { 46, 49 },
                                  new int[] { 35, 45 },
                                  new int[] { 11, 21 },
                                  new int[] { 31, 32 },
                                  new int[] { 16, 45 } },
                    0 },
                new object[] { 3,
                    new int[][] { new int[] { 44, 45 },
                                  new int[] { 1, 18 },
                                  new int[] { 11, 39 },
                                  new int[] { 34, 43 },
                                  new int[] { 7, 10 },
                                  new int[] { 16, 48 } },
                    0 },
                new object[] { 3,
                    new int[][] { new int[] { 44, 50 },
                                  new int[] { 22, 37 },
                                  new int[] { 46, 49 },
                                  new int[] { 35, 45 },
                                  new int[] { 11, 21 },
                                  new int[] { 31, 32 },
                                  new int[] { 16, 45 } },
                    0 },
                new object[] { 3,
                    EmbeddedResourceLoader.LoadJson<int[][]>("MostBookedTestData.LargeArray8.json"),
                    0 },
                new object[] { 4,
                    new int[][] { new int[] { 4, 15 } },
                    0 },
                new object[] { 4,
                    new int[][] { new int[] { 10, 11 },
                                  new int[] { 13, 15 },
                                  new int[] { 9, 19 },
                                  new int[] { 0, 12 },
                                  new int[] { 12, 20 } },
                    0 },
                new object[] { 4,
                    new int[][] { new int[] { 12, 44 },
                                  new int[] { 27, 37 },
                                  new int[] { 48, 49 },
                                  new int[] { 46, 49 },
                                  new int[] { 24, 44 },
                                  new int[] { 32, 38 },
                                  new int[] { 21, 49 },
                                  new int[] { 13, 30 } },
                    1 },
                new object[] { 4,
                    new int[][] { new int[] { 17, 19 } },
                    0 },
                new object[] { 4,
                    new int[][] { new int[] { 18, 19 } },
                    0 },
                new object[] { 4,
                    new int[][] { new int[] { 18, 19 },
                                  new int[] { 3, 12 },
                                  new int[] { 17, 19 },
                                  new int[] { 2, 13 },
                                  new int[] { 7, 10 } },
                    0 },
                new object[] { 4,
                    new int[][] { new int[] { 18, 20 },
                                  new int[] { 1, 5 } },
                    0 },
                new object[] { 4,
                    new int[][] { new int[] { 19, 20 },
                                  new int[] { 14, 15 },
                                  new int[] { 13, 14 },
                                  new int[] { 11, 20 } },
                    1 },
                new object[] { 4,
                    new int[][] { new int[] { 33, 42 },
                                  new int[] { 31, 44 },
                                  new int[] { 40, 48 },
                                  new int[] { 35, 42 },
                                  new int[] { 21, 22 },
                                  new int[] { 44, 46 },
                                  new int[] { 29, 32 } },
                    0 },
                new object[] { 4,
                    new int[][] { new int[] { 38, 44 },
                                  new int[] { 17, 38 },
                                  new int[] { 6, 29 },
                                  new int[] { 34, 40 },
                                  new int[] { 7, 14 },
                                  new int[] { 4, 27 } },
                    0 },
                new object[] { 4,
                    new int[][] { new int[] { 40, 47 },
                                  new int[] { 30, 36 },
                                  new int[] { 0, 8 },
                                  new int[] { 42, 44 },
                                  new int[] { 39, 49 },
                                  new int[] { 34, 44 } },
                    0 },
                new object[] { 4,
                    new int[][] { new int[] { 43, 49 },
                                  new int[] { 42, 43 },
                                  new int[] { 38, 44 },
                                  new int[] { 18, 24 },
                                  new int[] { 22, 38 },
                                  new int[] { 40, 49 },
                                  new int[] { 26, 45 } },
                    0 },
                new object[] { 4,
                    new int[][] { new int[] { 48, 49 },
                                  new int[] { 31, 40 },
                                  new int[] { 13, 44 },
                                  new int[] { 26, 44 },
                                  new int[] { 17, 41 },
                                  new int[] { 2, 4 },
                                  new int[] { 19, 41 },
                                  new int[] { 42, 44 } },
                    0 },
                new object[] { 4,
                    EmbeddedResourceLoader.LoadJson<int[][]>("MostBookedTestData.LargeArray4.json"),
                    2 },
                new object[] { 5,
                    new int[][] { new int[] { 0, 4 },
                                  new int[] { 14, 16 },
                                  new int[] { 1, 7 },
                                  new int[] { 6, 7 } },
                    0 },
                new object[] { 5,
                    new int[][] { new int[] { 3, 29 },
                                  new int[] { 7, 43 },
                                  new int[] { 48, 50 },
                                  new int[] { 20, 32 },
                                  new int[] { 38, 49 },
                                  new int[] { 22, 48 },
                                  new int[] { 41, 47 } },
                    0 },
                new object[] { 5,
                    new int[][] { new int[] { 10, 14 },
                                  new int[] { 13, 17 },
                                  new int[] { 3, 12 },
                                  new int[] { 6, 13 } },
                    0 },
                new object[] { 5,
                    new int[][] { new int[] { 12, 18 },
                                  new int[] { 8, 11 },
                                  new int[] { 19, 20 },
                                  new int[] { 5, 11 } },
                    0 },
                new object[] { 5,
                    new int[][] { new int[] { 31, 32 },
                                  new int[] { 13, 24 },
                                  new int[] { 32, 47 },
                                  new int[] { 41, 42 },
                                  new int[] { 38, 49 },
                                  new int[] { 17, 35 } },
                    0 },
                new object[] { 5,
                    new int[][] { new int[] { 33, 46 },
                                  new int[] { 29, 30 },
                                  new int[] { 40, 41 },
                                  new int[] { 23, 30 },
                                  new int[] { 10, 41 },
                                  new int[] { 25, 42 } },
                    1 },
                new object[] { 5,
                    new int[][] { new int[] { 37, 49 },
                                  new int[] { 27, 37 },
                                  new int[] { 0, 16 },
                                  new int[] { 12, 47 },
                                  new int[] { 46, 50 },
                                  new int[] { 4, 18 },
                                  new int[] { 10, 16 },
                                  new int[] { 15, 43 },
                                  new int[] { 21, 26 } },
                    0 },
                new object[] { 5,
                    new int[][] { new int[] { 40, 47 },
                                  new int[] { 7, 16 },
                                  new int[] { 27, 38 },
                                  new int[] { 16, 43 },
                                  new int[] { 38, 40 },
                                  new int[] { 2, 25 } },
                    0 },
                new object[] { 5,
                    new int[][] { new int[] { 43, 48 },
                                  new int[] { 17, 28 },
                                  new int[] { 23, 24 },
                                  new int[] { 16, 22 },
                                  new int[] { 6, 29 },
                                  new int[] { 5, 22 },
                                  new int[] { 45, 47 },
                                  new int[] { 44, 49 } },
                    0 },
                new object[] { 5,
                    EmbeddedResourceLoader.LoadJson<int[][]>("MostBookedTestData.LargeArray5.json"),
                    1 },
                new object[] { 10,
                    EmbeddedResourceLoader.LoadJson<int[][]>("MostBookedTestData.LargeArray3.json"),
                    1 },
                new object[] { 92,
                    EmbeddedResourceLoader.LoadJson<int[][]>("MostBookedTestData.LargeArray6.json"),
                    0 },
                new object[] { 94,
                    new int[][] { new int[] { 89, 215 },
                                  new int[] { 269, 401 },
                                  new int[] { 327, 464 },
                                  new int[] { 102, 134 },
                                  new int[] { 332, 336 },
                                  new int[] { 4, 184 },
                                  new int[] { 98, 418 },
                                  new int[] { 177, 441 },
                                  new int[] { 150, 465 },
                                  new int[] { 118, 418 },
                                  new int[] { 79, 148 },
                                  new int[] { 172, 201 },
                                  new int[] { 40, 60 } },
                    1 },
                new object[] { 94,
                    EmbeddedResourceLoader.LoadJson<int[][]>("MostBookedTestData.LargeArray7.json"),
                    1 },
                new object[] { 97,
                    new int[][] { new int[] { 70, 381 },
                                  new int[] { 250, 493 },
                                  new int[] { 4, 383 },
                                  new int[] { 246, 414 } },
                    0 },
                new object[] { 97,
                    new int[][] { new int[] {432,463 },
                                  new int[] { 50,258 },
                                  new int[] { 168,486 },
                                  new int[] { 379,463 },
                                  new int[] { 315,323 },
                                  new int[] { 176,408 },
                                  new int[] { 8,280 },
                                  new int[] { 146,486 },
                                  new int[] { 345,435 },
                                  new int[] { 318,329 },
                                  new int[] { 118,287 },
                                  new int[] { 473,481 },
                                  new int[] { 486,489 },
                                  new int[] { 449,453 },
                                  new int[] { 79,364 },
                                  new int[] { 468,494 },
                                  new int[] { 326,455 },
                                  new int[] { 11,217 },
                                  new int[] { 24,438 },
                                  new int[] { 215,241 },
                                  new int[] { 463,486 },
                                  new int[] { 169,237 },
                                  new int[] { 324,394 },
                                  new int[] { 120,377 },
                                  new int[] { 1,442 },
                                  new int[] { 479,490 },
                                  new int[] { 241,292 },
                                  new int[] { 182,203 },
                                  new int[] { 179,266 },
                                  new int[] { 21,170 },
                                  new int[] { 55,264 },
                                  new int[] { 183,349 },
                                  new int[] { 349,479 },
                                  new int[] { 116,242 },
                                  new int[] { 393,450 },
                                  new int[] { 236,298 },
                                  new int[] { 257,460 },
                                  new int[] { 443,451 } },
                    2 },
                new object[] { 100,
                    new int[][] { new int[] { 0, 1 } },
                    0 },
                new object[] { 100,
                    new int[][] { new int[] { 0, 10 },
                                  new int[] { 1, 5 },
                                  new int[] { 2, 7 },
                                  new int[] { 3, 4 } },
                    0 },
                new object[] { 100,
                    EmbeddedResourceLoader.LoadJson<int[][]>("MostBookedTestData.LargeArray1.json"),
                    99 },
                new object[] { 100,
                    EmbeddedResourceLoader.LoadJson<int[][]>("MostBookedTestData.LargeArray2.json"),
                    15 },
            };

            return result;
        }
    }
}