name: Build and test the solution

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1

    - name: Restore dependencies
      run: dotnet restore ${{ github.workspace }}\JobSearchCodeExamples\JobSearchCodeExamples.sln --verbosity detailed
      
    - name: Build
      run: msbuild ${{ github.workspace }}\JobSearchCodeExamples\JobSearchCodeExamples.sln -t:build -p:Configuration=Debug -p:Platform=x64

    - name: Test
      run: vstest.console.exe ${{ github.workspace }}\JobSearchCodeExamples\**\*.test.dll /ResultsDirectory:${{ github.workspace }}\TestResults /InIsolation /Platform:x64 /Framework:.NETFramework,Version=v6.0 /parallel /Enablecodecoverage /Logger:trx /TestAdapterPath:"${{ USERPROFILE }}\.nuget\packages\"
