name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore dependencies
      run: dotnet restore ./JobSearchCodeExamples/JobSearchCodeExamples.sln --verbosity detailed
    - name: Build
      run: msbuild ./JobSearchCodeExamples/JobSearchCodeExamples.sln -t:build -verbosity:diag -property:Configuration=Debug

    - name: Test
      run: dotnet test ./JobSearchCodeExamples/JobSearchCodeExamples.sln --no-build --verbosity normal
