name: Build and test the solution

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:

    runs-on: windows-2025-vs2026

    steps:
    - uses: actions/checkout@v5
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
        
    - name: Add MSBuild to PATH (Windows)
      uses: microsoft/setup-msbuild@v3

    - name: Get .NET information
      run: dotnet --info

    - name: Restore dependencies
      run: dotnet restore ${{ github.workspace }}\JobSearchCodeExamples\JobSearchCodeExamples.sln --verbosity detailed
      
    - name: Build
      run: msbuild ${{ github.workspace }}\JobSearchCodeExamples\JobSearchCodeExamples.sln -t:build -p:Configuration=Debug -p:Platform=x64
      
    - name: Test JobSearchCodeExamples.cpp.Test
      run: dotnet test ${{ github.workspace }}\JobSearchCodeExamples\JobSearchCodeExamples.cpp.Test\JobSearchCodeExamples.cpp.Test.csproj -p:Configuration=Debug -p:Platform=x64 --verbosity detailed --results-directory ${{ github.workspace }}\TestResults --no-build

    - name: Test JobSearchCodeExamples.cs.Test
      run: dotnet test ${{ github.workspace }}\JobSearchCodeExamples\JobSearchCodeExamples.Test\JobSearchCodeExamples.cs.Test.csproj -p:Configuration=Debug -p:Platform=x64 --verbosity detailed --results-directory ${{ github.workspace }}\TestResults --no-build

    - name: Test JobSearchCodeExamples.VB.Test
      run: dotnet test ${{ github.workspace }}\JobSearchCodeExamples\JobSearchCodeExamples.VB.Test\JobSearchCodeExamples.VB.Test.vbproj -p:Configuration=Debug -p:Platform=x64 --verbosity detailed --results-directory ${{ github.workspace }}\TestResults --no-build

    - name: Test JobSearchCodeExamples.FSharp.Test
      run: dotnet test ${{ github.workspace }}\JobSearchCodeExamples\JobSearchCodeExamples.FSharp.Test\JobSearchCodeExamples.fs.Test.fsproj -p:Configuration=Debug -p:Platform=x64 --verbosity detailed --results-directory ${{ github.workspace }}\TestResults --no-build
