name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Setup C++ to build correctly
      run: setx VCTargetsPath "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140" /M
    - name: Restore dependencies
      run: dotnet restore ./JobSearchCodeExamples/JobSearchCodeExamples.sln --verbosity detailed
    - name: Build
      run: dotnet build ./JobSearchCodeExamples/JobSearchCodeExamples.sln --no-restore
    - name: Test
      run: dotnet test ./JobSearchCodeExamples/JobSearchCodeExamples.sln --no-build --verbosity normal
